const film = [
    {
        name:"Avengers",
        pp:"https://fr.web.img6.acsta.net/c_310_420/medias/nmedia/18/85/31/58/20042068.jpg",
        url:"https://uqload.com/embed-0cmkr66zwzkm.html",
        des:"Lorsque Nick Fury, le directeur du S.H.I.E.L.D., l'organisation qui préserve la paix au plan mondial, cherche à former une équipe de choc pour empêcher la destruction du monde, Iron Man, Hulk, Thor, Captain America, Hawkeye et Black Widow répondent présents. Les Avengers ont beau constituer la plus fantastique des équipes, il leur reste encore à apprendre à travailler ensemble, et non les uns contre les autres, d'autant que le redoutable Loki a réussi à accéder au Cube Cosmique et à son pouvoir illimité...",
        date:"2012 / 2h 23min / Action, Aventure, Science fiction",
        star:"4.1",
    }, {
        name:"Avengers 2",
        pp:"https://fr.web.img2.acsta.net/c_310_420/pictures/15/02/24/18/29/161927.jpg",
        url:"https://uqload.com/embed-oimk5gvxf5kv.html",
        des:"Alors que Tony Stark tente de relancer un programme de maintien de la paix jusque-là suspendu, les choses tournent mal et les super-héros Iron Man, Captain America, Thor, Hulk, Black Widow et Hawkeye vont devoir à nouveau unir leurs forces pour combattre le plus puissant de leurs adversaires :le terrible Ultron, un être technologique terrifiant qui s’est juré d’éradiquer l’espèce humaine.Afin d’empêcher celui-ci d’accomplir ses sombres desseins, des alliances inattendues se scellent, les entraînant dans une incroyable aventure et une haletante course contre le temps…",
        date:"2015 / 2h 21min / Action, Aventure, Science fiction",
        star:"3.8",
    }, {
        name:"Avengers 3",
        pp:"https://fr.web.img3.acsta.net/c_310_420/pictures/18/03/16/14/42/0611719.jpg",
        url:"https://uqload.com/embed-tgjvcb27n37t.html",
        des:"Les Avengers et leurs alliés devront être prêts à tout sacrifier pour neutraliser le redoutable Thanos avant que son attaque éclair ne conduise à la destruction complète de l’univers",
        date:"2018 / 2h 36min / Aventure, Action, Fantastique",
        star:"4.3",
    }, {
        name:"Avengers 4",
        pp:"https://fr.web.img6.acsta.net/c_310_420/pictures/19/04/04/09/04/0472053.jpg",
        url:"https://uqload.com/embed-mzn8kib63wvz.html",
        des:"Thanos ayant anéanti la moitié de l’univers, les Avengers restants resserrent les rangs dans ce vingt-deuxième film des Studios Marvel, grande conclusion d’un des chapitres de l’Univers Cinématographique Marvel.",
        date:"2019/ 3h 01min / Action, Fantastique, Aventure",
        star:"4.2",
    }, {
        name:"ANT Man",
        pp:"https://fr.web.img2.acsta.net/c_310_420/pictures/15/05/06/16/05/305731.jpg",
        url:"https://uqload.com/embed-901sk7xm7e7p.html",
        des:"Scott Lang, cambrioleur de haut vol, va devoir apprendre à se comporter en héros et aider son mentor, le Dr Hank Pym, à protéger le secret de son spectaculaire costume d’Ant-Man, afin d’affronter une effroyable menace…REGARDER CE FILM",
        date:"2015 / 1h 57min / Action, Science fiction",
        star:"3.8",
    }, {
        name:"Spider Man",
        pp:"https://fr.web.img3.acsta.net/c_310_420/medias/nmedia/00/00/00/33/spiderman.jpg",
        url:"https://uqload.com/embed-biaptbc9tnyv.html",
        des:"Orphelin, Peter Parker est élevé par sa tante May et son oncle Ben dans le quartier Queens de New York. Tout en poursuivant ses études à l'université, il trouve un emploi de photographe au journal Daily Bugle. Il partage son appartement avec Harry Osborn, son meilleur ami, et rêve de séduire la belle Mary Jane.Cependant, après avoir été mordu par une araignée génétiquement modifiée, Peter voit son agilité et sa force s'accroître et se découvre des pouvoirs surnaturels. Devenu Spider Man, il décide d'utiliser ses nouvelles capacités au service du bien.Au même moment, le père de Harry, le richissime industriel Norman Osborn, est victime d'un accident chimique qui a démesurément augmenté ses facultés intellectuelles et sa force, mais l'a rendu fou. Il est devenu le Bouffon Vert, une créature démoniaque qui menace la ville. Entre lui et Spider Man, une lutte sans merci s'engage.",
        date:"2002 / 2h 01min / Fantastique, Action",
        star:"4.0",
    },{
        name:"Spider Man 2",
        pp:"https://fr.web.img2.acsta.net/c_310_420/medias/nmedia/18/35/16/02/18380826.jpg",
        url:"https://uqload.com/embed-xx6ix7ywmg98.html",
        des:"Ecartelé entre son identité secrète de Spider Man et sa vie d'étudiant, Peter Parker n'a pas réussi à garder celle qu'il aime, Mary Jane, qui est aujourd'hui comédienne et fréquente quelqu'un d'autre. Guidé par son seul sens du devoir, Peter vit désormais chacun de ses pouvoirs à la fois comme un don et comme une malédiction. Par ailleurs, l'amitié entre Peter et Harry Osborn est elle aussi menacée. Harry rêve plus que jamais de se venger de Spider Man, qu'il juge responsable de la mort de son père. La vie de Peter se complique encore lorsque surgit un nouvel ennemi :le redoutable Dr Otto Octavius. Cerné par les choix et les épreuves qui engagent aussi bien sa vie intime que l'avenir du monde, Peter doit affronter son destin et faire appel à tous ses pouvoirs afin de se battre sur tous les fronts...",
        date:"2004 / 2h 07min / Fantastique, Action",
        star:"3.8",
    },{
        name:"Spider Man 3",
        pp:"https://fr.web.img6.acsta.net/c_310_420/medias/nmedia/18/35/62/65/18754165.jpg",
        url:"https://uqload.com/embed-fcwaedo6w9ft.html",
        des:"Peter Parker a enfin réussi à concilier son amour pour Mary-Jane et ses devoirs de super-héros. Mais l'horizon s'obscurcit. La brutale mutation de son costume, qui devient noir, décuple ses pouvoirs et transforme également sa personnalité pour laisser ressortir l'aspect sombre et vengeur que Peter s'efforce de contrôler.Sous l'influence de son costume, Peter devient trop sûr de lui et commence à négliger ses proches. Contraint de choisir entre le pouvoir si séduisant de ce nouveau costume et la compassion qui le caractérisait avant, Peter va faire face à ses démons lorsqu'il affrontera deux des pires méchants de l'histoire, l'Homme-sable et Vénom, dont l'extraordinaire puissance et la soif de vengeance menacent Peter et tous ceux qui lui sont chers.",
        date:"2007 / 2h 19min / Fantastique, Action",
        star:"3.5",
    },{
        name:"The Amazing Spider Man",
        pp:"https://fr.web.img4.acsta.net/c_310_420/medias/nmedia/18/83/19/35/20158079.jpg",
        url:"https://uqload.com/embed-sqt2zp80lxuv.html",
        des:"Abandonné par ses parents lorsqu’il était enfant, Peter Parker a été élevé par son oncle Ben et sa tante May. Il est aujourd’hui au lycée, mais il a du mal à s’intégrer. Comme la plupart des adolescents de son âge, Peter essaie de comprendre qui il est et d’accepter son parcours. Amoureux pour la première fois, lui et Gwen Stacy découvrent les sentiments, l’engagement et les secrets. En retrouvant une mystérieuse mallette ayant appartenu à son père, Peter entame une quête pour élucider la disparition de ses parents, ce qui le conduit rapidement à Oscorp et au laboratoire du docteur Curt Connors, l’ancien associé de son père. Spider Man va bientôt se retrouver face au Lézard, l’alter ego de Connors. En décidant d’utiliser ses pouvoirs, il va choisir son destin…",
        date:"2012 / 2h 17min / Action, Fantastique, Aventure",
        star:"3.5",
    },{
        name:"The Amazing Spider Man 2",
        pp:"https://fr.web.img2.acsta.net/c_310_420/pictures/14/04/08/14/38/427284.jpg",
        url:" https://uqload.com/embed-uy0zehqh9fjr.html",
        des:"Ce n’est un secret pour personne que le combat le plus rude de Spider Man est celui qu’il mène contre lui-même en tentant de concilier la vie quotidienne de Peter Parker et les lourdes responsabilités de Spider Man. Mais Peter Parker va se rendre compte qu’il fait face à un conflit de bien plus grande ampleur. Être Spider Man, quoi de plus grisant ? Peter Parker trouve son bonheur entre sa vie de héros, bondissant d’un gratte-ciel à l’autre, et les doux moments passés aux côté de Gwen. Mais être Spider Man a un prix :il est le seul à pouvoir protéger ses concitoyens new-yorkais des abominables méchants qui menacent la ville.  Face à Electro, Peter devra affronter un ennemi nettement plus puissant que lui.  Au retour de son vieil ami Harry Osborn, il se rend compte que tous ses ennemis ont un point commun :OsCorp.",
        date:"2014 / 2h 17min / Action, Fantastique, Aventure",
        star:"3.5",
    }, {
        name:"Spider Man: Homecoming",
        pp:"https://fr.web.img6.acsta.net/c_310_420/pictures/17/05/24/15/35/100661.jpg",
        url:"https://uqload.com/embed-mtxpgt2267pr.html",
        des:"Après ses spectaculaires débuts dans Captain America :Civil War, le jeune Peter Parker découvre peu à peu sa nouvelle identité, celle de Spider Man, le super-héros lanceur de toile. Galvanisé par son expérience avec les Avengers, Peter rentre chez lui auprès de sa tante May, sous l’œil attentif de son nouveau mentor, Tony Stark. Il s’efforce de reprendre sa vie d’avant, mais au fond de lui, Peter rêve de se prouver qu’il est plus que le sympathique super héros du quartier. L’apparition d’un nouvel ennemi, le Vautour, va mettre en danger tout ce qui compte pour lui...",
        date:"2017 / 2h 13min / Action, Aventure",
        star:"3.5",
    }, {
        name:"Spider Man: Far From Home",
        pp:"https://fr.web.img3.acsta.net/c_310_420/pictures/19/06/13/15/28/4575985.jpg",
        url:"https://uqload.com/embed-58ixlp9konzu.html",
        des:"L'araignée sympa du quartier décide de rejoindre ses meilleurs amis Ned, MJ, et le reste de la bande pour des vacances en Europe. Cependant, le projet de Peter de laisser son costume de super-héros derrière lui pendant quelques semaines est rapidement compromis quand il accepte à contrecoeur d'aider Nick Fury à découvrir le mystère de plusieurs attaques de créatures, qui ravagent le continent !",
        date:"2019 / 2h 10min / Action, Aventure",
        star:"3.8",
    }, {
        name:"Spider Man: No Way Home",
        pp:"https://fr.web.img2.acsta.net/c_310_420/pictures/21/11/16/10/01/4860598.jpg",
        url:"https://uqload.com/embed-k382kifkc4fk.html",
        des:"Pour la première fois dans son histoire cinématographique, Spider Man, le héros sympa du quartier est démasqué et ne peut désormais plus séparer sa vie normale de ses lourdes responsabilités de super-héros. Quand il demande de l'aide à Doctor Strange, les enjeux deviennent encore plus dangereux, le forçant à découvrir ce qu'être Spider Man signifie véritablement.",
        date:"2021 / 2h 28min / Action, Aventure, Fantastique",
        star:"4.0",
    }, {
        name:"Batman 1989",
        pp:"https://fr.web.img3.acsta.net/c_310_420/pictures/22/02/16/17/42/3125788.jpg",
        url:"https://uqload.com/embed-rbsn2h5em728.html",
        des:"",
        date:"1989",
    },{
        name:"Batman 1992",
        pp:"https://fr.web.img3.acsta.net/c_310_420/pictures/22/02/16/17/42/3125788.jpg",
        url:"https://uqload.com/embed-eihqk3htrw9w.html",
        des:"",
        date:"1992",
    },{
        name:"Batman 1995",
        pp:"https://fr.web.img3.acsta.net/c_310_420/pictures/22/02/16/17/42/3125788.jpg",
        url:"https://uqload.com/embed-fymy52whdq09.html",
        des:"",
        date:"1995",
    },{
        name:"Batman 1997",
        pp:"https://fr.web.img3.acsta.net/c_310_420/pictures/22/02/16/17/42/3125788.jpg",
        url:"https://uqload.com/embed-usqbhki7mg60.html",
        des:"",
        date:"1997",
    },{
        name:"Batman 2005",
        pp:"https://fr.web.img3.acsta.net/c_310_420/pictures/22/02/16/17/42/3125788.jpg",
        url:"https://uqload.com/embed-pr301aiuguad.html",
        des:"",
        date:"2005",
    },{
        name:"Batman 2008",
        pp:"https://fr.web.img3.acsta.net/c_310_420/pictures/22/02/16/17/42/3125788.jpg",
        url:"https://uqload.com/embed-ya2g9qv585hi.html",
        des:"",
        date:"2008",
    },{
        name:"Batman 2012",
        pp:"https://fr.web.img3.acsta.net/c_310_420/pictures/22/02/16/17/42/3125788.jpg",
        url:"https://uqload.com/embed-079izxiswc2o.html",
        des:"",
        date:"2012",
    },{
        name:"Batman 2016",
        pp:"https://fr.web.img3.acsta.net/c_310_420/pictures/22/02/16/17/42/3125788.jpg",
        url:"https://uqload.com/embed-rtogisakheqt.html",
        des:"",
        date:"2016",
    },{
        name:"Les Gardiens de la Galaxie 1",
        pp:"https://fr.web.img3.acsta.net/c_310_420/pictures/14/08/04/15/09/405662.jpg",
        url:"https://uqload.com/embed-u16u5g59uvot.html",
        des:"Peter Quill est un aventurier traqué par tous les chasseurs de primes pour avoir volé un mystérieux globe convoité par le puissant Ronan, dont les agissements menacent l’univers tout entier. Lorsqu’il découvre le véritable pouvoir de ce globe et la menace qui pèse sur la galaxie, il conclut une alliance fragile avec quatre aliens disparates :Rocket, un raton laveur fin tireur, Groot, un humanoïde semblable à un arbre, l’énigmatique et mortelle Gamora, et Drax le Destructeur, qui ne rêve que de vengeance. En les ralliant à sa cause, il les convainc de livrer un ultime combat aussi désespéré soit-il pour sauver ce qui peut encore l’être …",
        date:"2014 / 2h 01min / Science fiction, Action",
        star:"4.2",
    }, {
        name:"Les Gardiens de la Galaxie 2",
        pp:"https://fr.web.img6.acsta.net/c_310_420/pictures/17/03/01/11/10/438835.jpg",
        url:"https://uqload.com/embed-d9nnvff388xj.html",
        des:"Musicalement accompagné de la \"Awesome Mixtape n°2\" (la musique qu'écoute Star-Lord dans le film), Les Gardiens de la galaxie 2 poursuit les aventures de l'équipe alors qu'elle traverse les confins du cosmos. Les gardiens doivent combattre pour rester unis alors qu'ils découvrent les mystères de la filiation de Peter Quill. Les vieux ennemis vont devenir de nouveaux alliés et des personnages bien connus des fans de comics vont venir aider nos héros et continuer à étendre l'univers Marvel.",
        date:"2017 / 2h 16min / Action, Science fiction, Comédie",
        star:"4.1",
    }, {
        name:"Shang Chi",
        pp:"https://fr.web.img6.acsta.net/c_310_420/pictures/21/08/25/11/54/3128925.jpg",
        url:"https://uqload.com/embed-jfriyaqrguqh.html",
        des:"Shang-Chi va devoir affronter un passé qu’il pensait avoir laissé derrière lui lorsqu’il est pris dans la toile de la mystérieuse organisation des dix anneaux.      ",
        date:"2021 / 2h 12min / Action, Fantastique",
        star:"3.9",
    }, {
        name:"Doctor Strange",
        pp:"https://fr.web.img6.acsta.net/c_310_420/pictures/16/09/09/08/57/518191.jpg",
        url:"https://uqload.com/embed-n5tka0oklesj.html",
        des:"Doctor Strange suit l'histoire du Docteur Stephen Strange, talentueux neurochirurgien qui, après un tragique accident de voiture, doit mettre son égo de côté et apprendre les secrets d'un monde caché de mysticisme et de dimensions alternatives. Basé à New York, dans le quartier de Greenwich Village, Doctor Strange doit jouer les intermédiaires entre le monde réel et ce qui se trouve au-delà, en utlisant un vaste éventail d'aptitudes métaphysiques et d'artefacts pour protéger le Marvel Cinematic Universe.",
        date:"2016 / 1h 55min / Fantastique, Aventure",
        star:"3.9",
    }, {
        name:"Doctor Strange 2",
        pp:"https://fr.web.img3.acsta.net/c_310_420/pictures/22/04/08/10/30/1779137.jpg",
        url:"https://uqload.com/embed-u3ytsirxo8og.html",
        des:"Dans ce nouveau film Marvel Studios, l’univers cinématographique Marvel déverrouille et repousse les limites du multivers encore plus loin. Voyagez dans l’inconnu avec Doctor Strange, qui avec l’aide d’anciens et de nouveaux alliés mystiques, traverse les réalités hallucinantes et dangereuses du multivers pour affronter un nouvel adversaire mystérieux.",
        date:"2022 / 2h 06min / Fantastique, Action, Aventure",
        star:"3.9",
    },{
        name:"Deadpool",
        pp:"https://fr.web.img2.acsta.net/c_310_420/pictures/16/01/19/16/49/249124.jpg",
        url:"https://uqload.com/embed-c4m7pnhixg0u.html",
        des:"Deadpool, est l'anti-héros le plus atypique de l'univers Marvel. A l'origine, il s'appelle Wade Wilson :un ancien militaire des Forces Spéciales devenu mercenaire. Après avoir subi une expérimentation hors norme qui va accélérer ses pouvoirs de guérison, il va devenir Deadpool. Armé de ses nouvelles capacités et d'un humour noir survolté, Deadpool va traquer l'homme qui a bien failli anéantir sa vie.",
        date:"2016 / 1h 48min / Comédie, Action, Fantastique",
        star:"4.0",
    },{
        name:"Deadpool 2",
        pp:"https://fr.web.img2.acsta.net/c_310_420/pictures/18/04/06/16/26/2317955.jpg",
        url:"https://uqload.com/embed-93hpsbfhh29v.html",
        des:"L’insolent mercenaire de Marvel remet le masque ! Plus grand, plus-mieux, et occasionnellement les fesses à l’air, il devra affronter un Super-Soldat dressé pour tuer, repenser l’amitié, la famille, et ce que signifie l’héroïsme – tout en bottant cinquante nuances de culs, car comme chacun sait, pour faire le Bien, il faut parfois se salir les doigts.",
        date:"2018 / 2h 00min / Action, Comédie, Aventure",
        star:"3.9",
    },{
        name:"Wonder Woman",
        pp:"https://fr.web.img6.acsta.net/c_310_420/pictures/17/05/09/17/15/350974.jpg",
        url:"https://uqload.com/embed-8g9v4ho4royv.html",
        des:"C'était avant qu'elle ne devienne Wonder Woman, à l'époque où elle était encore Diana, princesse des Amazones et combattante invincible. Un jour, un pilote américain s'écrase sur l'île paradisiaque où elle vit, à l'abri des fracas du monde. Lorsqu'il lui raconte qu'une guerre terrible fait rage à l'autre bout de la planète, Diana quitte son havre de paix, convaincue qu'elle doit enrayer la menace. En s'alliant aux hommes dans un combat destiné à mettre fin à la guerre, Diana découvrira toute l'étendue de ses pouvoirs… et son véritable destin.",
        date:"2017 / 2h 21min / Action, Aventure, Fantastique",
        star:"3.7",
    },{
        name:"Wonder Woman 2",
        pp:"https://fr.web.img2.acsta.net/c_310_420/pictures/20/12/07/17/38/1866668.jpg",
        url:"https://uqload.com/embed-tldqh3tk9p0k.html",
        des:"Suite des aventures de Diana Prince, alias Wonder Woman, Amazone devenue une super-héroïne dans notre monde. Après la Première guerre mondiale, direction les années 80 ! Cette fois, Wonder Woman doit affronter deux nouveaux ennemis, particulièrement redoutables :Max Lord et Cheetah.",
        date:"2021 / 2h 31min / Action, Aventure, Fantastique",
        star:"2.1",
    },{
        name:"Justice League",
        pp:"https://fr.web.img5.acsta.net/c_310_420/pictures/17/10/31/10/29/4837499.jpg",
        url:"https://uqload.com/embed-mnbo80h3wrmx.html",
        des:"Après avoir retrouvé foi en l'humanité, Bruce Wayne, inspiré par l'altruisme de Superman, sollicite l'aide de sa nouvelle alliée, Diana Prince, pour affronter un ennemi plus redoutable que jamais. Ensemble, Batman et Wonder Woman ne tardent pas à recruter une équipe de méta-humains pour faire face à cette menace inédite. Pourtant, malgré la force que représente cette ligue de héros sans précédent – Batman, Wonder Woman, Aquaman, Cyborg et Flash –, il est peut-être déjà trop tard pour sauver la planète d'une attaque apocalyptique…      ",
        date:"2017 / 2h 00min / Action, Science fiction",
        star:"2.8",
    },{
        name:"Man of Steel",
        pp:"https://fr.web.img6.acsta.net/c_310_420/pictures/210/081/21008110_20130524125237634.jpg",
        url:"https://uqload.com/embed-n4udhnu3todq.html",
        des:"Un petit garçon découvre qu'il possède des pouvoirs surnaturels et qu'il n'est pas né sur Terre. Plus tard, il s'engage dans un périple afin de comprendre d'où il vient et pourquoi il a été envoyé sur notre planète. Mais il devra devenir un héros s'il veut sauver le monde de la destruction totale et incarner l'espoir pour toute l'humanité.",
        date:"2013 / 2h 23min / Action, Aventure, Fantastique",
        star:"3.6",
    },{
        name:"Thor",
        pp:"https://fr.web.img6.acsta.net/c_310_420/medias/nmedia/18/77/96/35/19701393.jpg",
        url:"https://uqload.com/embed-732mp2061r6f.html",
        des:"Thor :Le Monde des ténèbres nous entraîne dans les nouvelles aventures de Thor, le puissant Avenger, qui lutte pour sauver la Terre et les neuf mondes d’un mystérieux ennemi qui convoite l’univers tout entier… Après les films Marvel Thor et Avengers, Thor se bat pour restaurer l’ordre dans le cosmos, mais une ancienne race, sous la conduite du terrible Malekith, un être assoiffé de vengeance, revient pour répandre les ténèbres. Confronté à un ennemi que même Odin et Asgard ne peuvent contrer, Thor doit s’engager dans son aventure la plus dangereuse et la plus personnelle, au cours de laquelle il va devoir s’allier au traître Loki pour sauver non seulement son peuple et ceux qui lui sont chers, mais aussi l’univers lui-même.      ",
        date:"2011 / 1h 52min / Action, Fantastique, Aventure",
        star:"3.4",
    },{
        name:"Thor 2",
        pp:"https://fr.web.img5.acsta.net/c_310_420/pictures/210/407/21040735_20130916181657638.jpg",
        url:"https://uqload.com/embed-remarup65952.html",
        des:"Thor :Le Monde des ténèbres nous entraîne dans les nouvelles aventures de Thor, le puissant Avenger, qui lutte pour sauver la Terre et les neuf mondes d’un mystérieux ennemi qui convoite l’univers tout entier… Après les films Marvel Thor et Avengers, Thor se bat pour restaurer l’ordre dans le cosmos, mais une ancienne race, sous la conduite du terrible Malekith, un être assoiffé de vengeance, revient pour répandre les ténèbres. Confronté à un ennemi que même Odin et Asgard ne peuvent contrer, Thor doit s’engager dans son aventure la plus dangereuse et la plus personnelle, au cours de laquelle il va devoir s’allier au traître Loki pour sauver non seulement son peuple et ceux qui lui sont chers, mais aussi l’univers lui-même.      ",
        date:"2013 / 1h 55min / Action, Fantastique, Aventure",
        star:"3.4",
    },{
        name:"Thor 3",
        pp:"https://fr.web.img6.acsta.net/c_310_420/pictures/17/08/24/17/34/098917.jpg",
        url:"https://uqload.com/embed-rxc2a94ms15v.html",
        des:"Privé de son puissant marteau, Thor est retenu prisonnier sur une lointaine planète aux confins de l’univers. Pour sauver Asgard, il va devoir lutter contre le temps afin d’empêcher l’impitoyable Hela d’accomplir le Ragnarök – la destruction de son monde et la fin de la civilisation asgardienne. Mais pour y parvenir, il va d’abord devoir mener un combat titanesque de gladiateurs contre celui qui était autrefois son allié au sein des Avengers :l’incroyable Hulk…",
        date:"2017 / 2h 11min / Action, Science fiction",
        star:"3.9",
    },{
        name:"Captain Marvel",
        pp:"https://fr.web.img6.acsta.net/c_310_420/pictures/18/12/03/08/53/5968896.jpg",
        url:"https://uqload.com/embed-7zp5j0m9h51j.html",
        des:"Captain Marvel raconte l’histoire de Carol Danvers qui va devenir l’une des super-héroïnes les plus puissantes de l’univers lorsque la Terre se révèle l’enjeu d’une guerre galactique entre deux races extraterrestres.",
        date:"2019 / 2h 04min / Action, Fantastique, Science fiction",
        star:"3.6",
    },{
        name:"Venom",
        pp:"https://fr.web.img6.acsta.net/c_310_420/pictures/18/09/20/10/41/4338768.jpg",
        url:"https://uqload.com/embed-vocjfkf0x3dt.html",
        des:"Possédé par un symbiote qui agit de manière autonome, le journaliste Eddie Brock devient le protecteur létal Venom.",
        date:"2018 / 1h 52min / Science fiction, Action",
        star:"3.2",
    },{
        name:"Venom 2",
        pp:"https://fr.web.img6.acsta.net/c_310_420/pictures/21/09/01/11/19/0900123.jpg",
        url:"https://uqload.com/embed-9mxqunbwjpvx.html",
        des:"Tom Hardy est de retour sur grand écran sous les traits de Venom, l'un des personnages les plus complexes de l'univers Marvel.",
        date:"2021 / 1h 38min / Action, Fantastique",
        star:"2.1",
    },{
        name:"Les Eternels",
        pp:"https://fr.web.img3.acsta.net/c_310_420/pictures/19/01/16/09/43/1763808.jpg",
        url:"https://uqload.com/embed-qnj0bfke40uj.html",
        des:"En 2001, la jeune Qiao est amoureuse de Bin, petit chef de la pègre locale de Datong. Alors que Bin est attaqué par une bande rivale, Qiao prend sa défense et tire plusieurs coups de feu. Elle est condamnée à cinq ans de prison. A sa sortie, Qiao part à la recherche de Bin et tente de renouer avec lui. Mais il refuse de la suivre. Dix ans plus tard, à Datong, Qiao est célibataire, elle a réussi sa vie en restant fidèle aux valeurs de la pègre. Bin, usé par les épreuves, revient pour retrouver Qiao, la seule personne qu’il ait jamais aimée…", 
        date:"27 février 2019",
    },{
        name:"Suicide squad",
        pp:"https://fr.web.img3.acsta.net/c_310_420/pictures/16/07/12/15/47/166170.jpg",
        url:"https://uqload.com/embed-49rb9c4xxkpb.html",
        des:"Les pires méchants de l’univers DC Comics réunis dans un même film.C'est tellement jouissif d'être un salopard ! Face à une menace aussi énigmatique qu'invincible, l'agent secret Amanda Waller réunit une armada de crapules de la pire espèce. Armés jusqu'aux dents par le gouvernement, ces Super-Méchants s'embarquent alors pour une mission-suicide. Jusqu'au moment où ils comprennent qu'ils ont été sacrifiés. Vont-ils accepter leur sort ou se rebeller ?", 
        date:"3 août 2016",
    },{
        name:"Suicide squad 2",
        pp:"https://fr.web.img5.acsta.net/c_310_420/pictures/21/03/26/16/42/1810776.jpg",
        url:"https://uqload.com/embed-9ggjiiptuy1y.html",
        des:"Bienvenue en enfer - aka Belle Reve, la prison dotée du taux de mortalité le plus élevé des États-Unis d'Amérique. Là où sont détenus les pires super-vilains, qui feront tout pour en sortir - y compris rejoindre la super secrète et la super louche Task Force X. La mission mortelle du jour ? Assemblez une belle collection d'escrocs, et notamment Bloodsport, Peacemaker, Captain Boomerang, Ratcatcher 2, Savant, King Shark, Blackguard, Javelin et la psychopathe préférée de tous :Harley Quinn. Armez-les lourdement et jetez-les (littéralement) sur l'île lointaine et bourrée d'ennemis de Corto Maltese. Traversant une jungle qui grouille d'adversaires et de guerilleros à chaque tournant, l'Escouade est lancée dans une mission de recherche et de destruction, avec le seul Colonel Rick Flag pour les encadrer sur le terrain… et la technologie du gouvernement dans leurs oreilles, afin qu'Amanda Waller puisse suivre le moindre de leurs mouvements. Comme toujours, un faux pas est synonyme de mort (que ce soit des mains de leurs opposants, d'un coéquipier ou de Waller elle-même). Si quelqu'un veut parier, mieux vaut miser contre eux - et contre eux tous.", 
        date:"28 juillet 2021",
    },{
        name:"Aquaman",
        pp:"https://fr.web.img5.acsta.net/c_310_420/pictures/18/12/13/12/12/2738771.jpg",
        url:"https://uqload.com/embed-vx0hpztpk8q6.html",
        des:"Les origines d’un héros malgré lui, dont le destin est d’unir deux mondes opposés, la terre et la mer. Cette histoire épique est celle d’un homme ordinaire destiné à devenir le roi des Sept Mers.", 
        date:"19 décembre 2018",
    },{
        name:"Hulk",
        pp:"https://fr.web.img4.acsta.net/c_310_420/medias/nmedia/00/02/54/34/affiche2.jpg",
        url:"https://uqload.com/embed-61cmy2p6unq1.html",
        des:"Au cours d'une opération scientifique qui a mal tourné, le docteur Bruce Banner est exposé à une surdose de radiations nucléaires. Miraculeusement indemne, il sort néanmoins affecté de cette douloureuse expérience et développe le pouvoir de se transformer en Hulk, un monstre vert à la force surhumaine et à la rage incontrôlable. Cette créature ne se manifeste que lorsque ce dernier est soumis à une intense émotion.Mis au ban de la société, le docteur Banner est obligé de se cacher pour ne pas faire subir aux autres sa métamorphose. Le général Ross, le père de Betty, l'ex-petite amie de Bruce, est chargé de stopper le monstre par tous les moyens. Glenn Talbot, rival scientifique de Banner, est également sur les traces de Hulk. Lorsque Betty découvre que la créature a un rapport avec les recherches du père de Bruce, elle devient la seule à pouvoir comprendre ce qu'est Hulk...", 
        date:"2 juillet 2003",
    },{
        name:"L'Incroyable Hulk",
        pp:"https://fr.web.img6.acsta.net/c_310_420/medias/nmedia/18/65/69/21/18949753.jpg",
        url:"https://uqload.com/embed-samixp0pbc7o.html",
        des:"Le scientifique Bruce Banner cherche désespérément un antidote aux radiations gamma qui ont créé Hulk. Il vit dans l'ombre, toujours amoureux de la belle Betty Ross et parcourt la planète à la recherche d'un remède.La force destructrice de Hulk attire le Général Thunderbolt Ross et son bras droit Blonsky qui rêvent de l'utiliser à des fins militaires. Ils tentent de développer un sérum pour créer des soldats surpuissants.De retour aux Etats-Unis, Bruce Banner se découvre un nouvel ennemi. Après avoir essayé le sérum expérimental, Blonsky est devenu L'Abomination, un monstre incontrôlable dont la force pure est même supérieure à celle de Hulk. Devenu fou, il s'est transformé en plein coeur de New York.Pour sauver la ville de la destruction totale, Bruce Banner va devoir faire appel au monstre qui sommeille en lui...", 
        date:"23 juillet 2008",
    },{
        name:"Green Lantern",
        pp:"https://fr.web.img2.acsta.net/c_310_420/medias/nmedia/18/71/59/31/19759992.jpg",
        url:"https://uqload.com/embed-plwsu5xas9ml.html",
        des:"Dans un univers aussi vaste que mystérieux, une force aussi petite que puissante est en place depuis des siècles :des protecteurs de la paix et de la justice appelés Green Lantern Corps, une confrérie de guerriers qui a juré de maintenir l’ordre intergalactique, et dont chaque membre porte un anneau lui conférant des super-pouvoirs. Mais quand un ennemi du nom de Parallax menace de rompre l’équilibre entre les forces de l’univers, leur destin et celui de la Terre repose sur leur dernière recrue, le premier humain jamais choisi :Hal Jordan. Hal est un pilote d’essai talentueux et imprudent, mais les Green Lanterns ont un peu de respect pour les humains, qui n’ont jamais exploité les pouvoirs infinis de l’anneau auparavant. Hal est clairement la pièce manquante du puzzle et il possède, en plus de sa détermination et de sa volonté, une chose qu’aucun des autres membres n’a jamais eu :son humanité. Soutenu par son amour d’enfance, le pilote Carol Ferris, Hal doit rapidement maîtriser ses nouveaux pouvoirs et vaincre ses peur, pour prouver qu’il n’est pas que la clé pour vaincre Parallax… mais peut-être le plus grand Green Lantern de tous les temps.", 
        date:"10 août 2011",
    },{
        name:"Bac Nord",
        pp:"https://fr.web.img6.acsta.net/c_310_420/pictures/21/06/07/13/11/2832970.jpg",
        url:"https://uqload.com/embed-cl96ijd3fnq5.html",
        des:"2012. Les quartiers Nord de Marseille détiennent un triste record :la zone au taux de criminalité le plus élevé de France. Poussée par sa hiérarchie, la BAC Nord, brigade de terrain, cherche sans cesse à améliorer ses résultats. Dans un secteur à haut risque, les flics adaptent leurs méthodes, franchissant parfois la ligne jaune. Jusqu'au jour où le système judiciaire se retourne contre eux…", 
        date:"18 août 2021",
    },{
        name:"Free Guy",
        pp:"https://fr.web.img2.acsta.net/c_310_420/pictures/21/06/23/18/09/1919284.jpg",
        url:"https://uqload.com/embed-sw2i9efsbd6b.html",
        des:"Un employé de banque, découvrant un jour qu’il n’est en fait qu’un personnage d’arrière-plan dans un jeu vidéo en ligne, décide de devenir le héros de sa propre histoire, quitte à la réécrire.", 
        date:"11 août 2021",
    },{
        name:"Red notice",
        pp:"https://fr.web.img4.acsta.net/c_310_420/pictures/21/10/21/15/41/2023058.jpg",
        url:"https://uqload.com/embed-cdqxqcrjzhlf.html",
        des:"Lorsqu’Interpol déclenche une Alerte Rouge – destinée à traquer et capturer les criminels les plus recherchés au monde –, le FBI fait appel à son meilleur profiler, John Hartley. Il se retrouve contraint de s’associer au plus grand voleur d’œuvres d’art au monde.", 
        date:"12 novembre 2021",
    },{
        name:"Star Wars 1",
        pp:"https://fr.web.img6.acsta.net/c_310_420/medias/nmedia/18/35/83/29/20017378.jpg",
        url:"https://uqload.com/embed-gv85blttit0v.html",
        des:"Avant de devenir un célèbre chevalier Jedi, et bien avant de se révéler l’âme la plus noire de la galaxie, Anakin Skywalker est un jeune esclave sur la planète Tatooine. La Force est déjà puissante en lui et il est un remarquable pilote de Podracer. Le maître Jedi Qui-Gon Jinn le découvre et entrevoit alors son immense potentiel.Pendant ce temps, l’armée de droïdes de l’insatiable Fédération du Commerce a envahi Naboo, une planète pacifique, dans le cadre d’un plan secret des Sith visant à accroître leur pouvoir. Pour défendre la reine de Naboo, Amidala, les chevaliers Jedi vont devoir affronter le redoutable Seigneur Sith, Dark Maul.", 
        date:"13 octobre 1999",
    },{
        name:"Star Wars 2",
        pp:"https://fr.web.img3.acsta.net/c_310_420/medias/nmedia/00/02/34/81/affclones.jpg",
        url:"https://uqload.com/embed-34iwobljd7ee.html",
        des:"Depuis le blocus de la planète Naboo par la Fédération du commerce, la République, gouvernée par le Chancelier Palpatine, connaît une véritable crise. Un groupe de dissidents, mené par le sombre Jedi comte Dooku, manifeste son mécontentement envers le fonctionnement du régime. Le Sénat et la population intergalactique se montrent pour leur part inquiets face à l'émergence d'une telle menace.Certains sénateurs demandent à ce que la République soit dotée d'une solide armée pour empêcher que la situation ne se détériore davantage. Parallèlement, Padmé Amidala, devenue sénatrice, est menacée par les séparatistes et échappe de justesse à un attentat. Le Padawan Anakin Skywalker est chargé de sa protection. Son maître, Obi-Wan Kenobi, part enquêter sur cette tentative de meurtre et découvre la constitution d'une mystérieuse armée de clones...", 
        date:"17 mai 2002",
    },{
        name:"Star Wars 3",
        pp:"https://fr.web.img6.acsta.net/c_310_420/medias/nmedia/18/35/53/23/18423997.jpg",
        url:"https://uqload.com/embed-0ljktzhh690z.html",
        des:"La Guerre des Clones fait rage. Une franche hostilité oppose désormais le Chancelier Palpatine au Conseil Jedi. Anakin Skywalker, jeune Chevalier Jedi pris entre deux feux, hésite sur la conduite à tenir. Séduit par la promesse d'un pouvoir sans précédent, tenté par le côté obscur de la Force, il prête allégeance au maléfique Darth Sidious et devient Dark Vador.Les Seigneurs Sith s'unissent alors pour préparer leur revanche, qui commence par l'extermination des Jedi. Seuls rescapés du massacre, Yoda et Obi Wan se lancent à la poursuite des Sith. La traque se conclut par un spectaculaire combat au sabre entre Anakin et Obi Wan, qui décidera du sort de la galaxie.", 
        date:"18 mai 2005",
    },{
        name:"Star Wars 4",
        pp:"https://fr.web.img5.acsta.net/c_310_420/medias/nmedia/18/35/41/59/18422600.jpg",
        url:"https://uqload.com/embed-ktddysf9gwew.html",
        des:"Il y a bien longtemps, dans une galaxie très lointaine... La guerre civile fait rage entre l'Empire galactique et l'Alliance rebelle. Capturée par les troupes de choc de l'Empereur menées par le sombre et impitoyable Dark Vador, la princesse Leia Organa dissimule les plans de l'Etoile Noire, une station spatiale invulnérable, à son droïde R2-D2 avec pour mission de les remettre au Jedi Obi-Wan Kenobi. Accompagné de son fidèle compagnon, le droïde de protocole C-3PO, R2-D2 s'échoue sur la planète Tatooine et termine sa quête chez le jeune Luke Skywalker. Rêvant de devenir pilote mais confiné aux travaux de la ferme, ce dernier se lance à la recherche de ce mystérieux Obi-Wan Kenobi, devenu ermite au coeur des montagnes désertiques de Tatooine...", 
        date:"19 octobre 1977",
    },{
        name:"Star Wars 5",
        pp:"https://fr.web.img2.acsta.net/c_310_420/medias/nmedia/00/02/44/28/empire.jpg",
        url:"https://uqload.com/embed-gu3632v3wl8m.html",
        des:"Malgré la destruction de l'Etoile Noire, l'Empire maintient son emprise sur la galaxie, et poursuit sans relâche sa lutte contre l'Alliance rebelle. Basés sur la planète glacée de Hoth, les rebelles essuient un assaut des troupes impériales. Parvenus à s'échapper, la princesse Leia, Han Solo, Chewbacca et C-3P0 se dirigent vers Bespin, la cité des nuages gouvernée par Lando Calrissian, ancien compagnon de Han. Suivant les instructions d'Obi-Wan Kenobi, Luke Skywalker se rend quant à lui vers le système de Dagobah, planète marécageuse où il doit recevoir l'enseignement du dernier maître Jedi, Yoda. Apprenant l'arrestation de ses compagnons par les stormtroopers de Dark Vador après la trahison de Lando, Luke décide d'interrompre son entraînement pour porter secours à ses amis et affronter le sombre seigneur Sith...", 
        date:"20 août 1980",
    },{
        name:"Star Wars 6",
        pp:"https://fr.web.img6.acsta.net/c_310_420/medias/nmedia/18/35/41/62/18422602.jpg",
        url:"https://uqload.com/embed-evpygcm7kbmb.html",
        des:"L'Empire galactique est plus puissant que jamais :la construction de la nouvelle arme, l'Etoile de la Mort, menace l'univers tout entier... Arrêté après la trahison de Lando Calrissian, Han Solo est remis à l'ignoble contrebandier Jabba Le Hutt par le chasseur de primes Boba Fett. Après l'échec d'une première tentative d'évasion menée par la princesse Leia, également arrêtée par Jabba, Luke Skywalker et Lando parviennent à libérer leurs amis.Han, Leia, Chewbacca, C-3PO et Luke, devenu un Jedi, s'envolent dès lors pour une mission d'extrême importance sur la lune forestière d'Endor, afin de détruire le générateur du bouclier de l'Etoile de la Mort et permettre une attaque des pilotes de l'Alliance rebelle. Conscient d'être un danger pour ses compagnons, Luke préfère se rendre aux mains de Dark Vador, son père et ancien Jedi passé du côté obscur de la Force.", 
        date:"19 octobre 1983",
    },{
        name:"Star Wars 7",
        pp:"https://fr.web.img2.acsta.net/c_310_420/pictures/15/10/18/18/56/052074.jpg",
        url:"https://uqload.com/embed-gy87vyby414z.html",
        des:"IDans une galaxie lointaine, très lointaine, un nouvel épisode de la saga Star Wars, 30 ans après les événements du Retour du Jedi.", 
        date:"16 décembre 2015",
    },{
        name:"Star Wars 8",
        pp:"https://fr.web.img4.acsta.net/c_310_420/pictures/17/10/10/04/58/2061488.jpg",
        url:"https://uqload.com/embed-vsmgq262kdbu.html",
        des:"Il y a bien longtemps, dans une galaxie très lointaine... La guerre civile fait rage entre l'Empire galactique et l'Alliance rebelle. Capturée par les troupes de choc de l'Empereur menées par le sombre et impitoyable Dark Vador, la princesse Leia Organa dissimule les plans de l'Etoile Noire, une station spatiale invulnérable, à son droïde R2-D2 avec pour mission de les remettre au Jedi Obi-Wan Kenobi. Accompagné de son fidèle compagnon, le droïde de protocole C-3PO, R2-D2 s'échoue sur la planète Tatooine et termine sa quête chez le jeune Luke Skywalker. Rêvant de devenir pilote mais confiné aux travaux de la ferme, ce dernier se lance à la recherche de ce mystérieux Obi-Wan Kenobi, devenu ermite au coeur des montagnes désertiques de Tatooine...", 
        date:"13 décembre 2017",
    },{
        name:"Star Wars 9",
        pp:"https://fr.web.img5.acsta.net/c_310_420/pictures/20/10/02/12/21/3764004.png",
        url:"https://uqload.com/embed-oj0jnh94fqos.html",
        des:"La conclusion de la saga Skywalker. De nouvelles légendes vont naître dans cette bataille épique pour la liberté.", 
        date:"18 décembre 2019",
    },{
        name:"Avatar",
        pp:"https://fr.web.img5.acsta.net/c_310_420/medias/nmedia/18/78/95/70/19485155.jpg",
        url:"https://uqload.com/embed-ow6devj0hdhk.html",
        des:"Malgré sa paralysie, Jake Sully, un ancien marine immobilisé dans un fauteuil roulant, est resté un combattant au plus profond de son être. Il est recruté pour se rendre à des années-lumière de la Terre, sur Pandora, où de puissants groupes industriels exploitent un minerai rarissime destiné à résoudre la crise énergétique sur Terre. Parce que l'atmosphère de Pandora est toxique pour les humains, ceux-ci ont créé le Programme Avatar, qui permet à des pilotes humains de lier leur esprit à un avatar, un corps biologique commandé à distance, capable de survivre dans cette atmosphère létale. Ces avatars sont des hybrides créés génétiquement en croisant l'ADN humain avec celui des Na'vi, les autochtones de Pandora.Sous sa forme d'avatar, Jake peut de nouveau marcher. On lui confie une mission d'infiltration auprès des Na'vi, devenus un obstacle trop conséquent à l'exploitation du précieux minerai. Mais tout va changer lorsque Neytiri, une très belle Na'vi, sauve la vie de Jake...", 
        date:"16 décembre 2009",
    },{
        name:"Harry Poter 1",
        pp:"https://fr.web.img6.acsta.net/c_310_420/pictures/18/07/02/17/25/3643090.jpg",
        url:"https://uqload.com/embed-w3wvt620zngq.html",
        des:"Le jour de son onzième anniversaire, Harry reçoit la visite inattendue d'un homme gigantesque se nommant Rubeus Hagrid. Celui-ci lui révèle qu'il est en fait le fils de deux puissants magiciens...", 
        date:"5 décembre 2001",
    },{
        name:"Harry Poter 2",
        pp:"https://fr.web.img2.acsta.net/c_310_420/medias/nmedia/00/02/53/35/affiche0.jpg",
        url:"https://uqload.com/embed-1lewn3mp95jc.html",
        des:"Alors que l'oncle Vernon, la tante Pétunia et son cousin Dudley reçoivent d'importants invités à dîner, Harry Potter est contraint de passer la soirée dans sa chambre. Dobby, un elfe, fait alors son apparition. Il lui annonce que de terribles dangers menacent l'école de Poudlard et qu'il ne doit pas y retourner en septembre. Harry refuse de le croire.Mais sitôt la rentrée des classes effectuée, ce dernier entend une voix malveillante. Celle-ci lui dit que la redoutable et légendaire Chambre des secrets est à nouveau ouverte, permettant ainsi à l'héritier de Serpentard de semer le chaos à Poudlard. Les victimes, retrouvées pétrifiées par une force mystérieuse, se succèdent dans les couloirs de l'école, sans que les professeurs - pas même le populaire Gilderoy Lockhart - ne parviennent à endiguer la menace. Aidé de Ron et Hermione, Harry doit agir au plus vite pour sauver Poudlard.", 
        date:"4 décembre 2002",
    },{
        name:"Harry Poter 3",
        pp:"https://fr.web.img5.acsta.net/c_310_420/medias/nmedia/18/35/23/41/18378380.jpg",
        url:"https://uqload.com/embed-6i6yll660koy.html",
        des:"Sirius Black, un dangereux sorcier criminel, s'échappe de la sombre prison d'Azkaban avec un seul et unique but :retrouver Harry Potter, en troisième année à l'école de Poudlard. Selon la légende, Black aurait jadis livré les parents du jeune sorcier à leur assassin, Lord Voldemort, et serait maintenant déterminé à tuer Harry...", 
        date:"2 juin 2004",
    },{
        name:"Harry Poter 4",
        pp:"https://fr.web.img6.acsta.net/c_310_420/medias/nmedia/18/35/52/34/18450888.jpg",
        url:"https://uqload.com/embed-bfrcu9g9d28r.html",
        des:"La quatrième année à l'école de Poudlard est marquée par le \"Tournoi des trois sorciers\". Les participants sont choisis par la fameuse \"coupe de feu\" qui est à l'origine d'un scandale. Elle sélectionne Harry Potter alors qu'il n'a pas l'âge légal requis !Accusé de tricherie et mis à mal par une série d'épreuves physiques de plus en plus difficiles, ce dernier sera enfin confronté à Celui dont on ne doit pas prononcer le nom, Lord V.", 
        date:"30 novembre 2005",
    },{
        name:"Harry Poter 5",
        pp:"https://fr.web.img4.acsta.net/c_310_420/medias/nmedia/18/36/32/70/18778375.jpg",
        url:"https://uqload.com/embed-pf7iae4ys05z.html",
        des:"Alors qu'il entame sa cinquième année d'études à Poudlard, Harry Potter découvre que la communauté des sorciers ne semble pas croire au retour de Voldemort, convaincue par une campagne de désinformation orchestrée par le Ministre de la Magie Cornelius Fudge. Afin de le maintenir sous surveillance, Fudge impose à Poudlard un nouveau professeur de Défense contre les Forces du Mal, Dolorès Ombrage, chargée de maintenir l'ordre à l'école et de surveiller les faits et gestes de Dumbledore. Prodiguant aux élèves des cours sans grand intérêt, celle qui se fait appeler la Grande Inquisitrice de Poudlard semble également décidée à tout faire pour rabaisser Harry. Entouré de ses amis Ron et Hermione, ce dernier met sur pied un groupe secret, \"L'Armée de Dumbledore\", pour leur enseigner l'art de la défense contre les forces du Mal et se préparer à la guerre qui s'annonce...", 
        date:"11 juillet 2007",
    },{
        name:"Harry Poter 6",
        pp:"https://fr.web.img6.acsta.net/c_310_420/medias/nmedia/18/65/64/35/19116952.jpg",
        url:"https://uqload.com/embed-rs40uk1813in.html",
        des:"L'étau démoniaque de Voldemort se resserre sur l'univers des Moldus et le monde de la sorcellerie. Poudlard a cessé d'être un havre de paix, le danger rode au coeur du château... Mais Dumbledore est plus décidé que jamais à préparer Harry à son combat final, désormais imminent. Ensemble, le vieux maître et le jeune sorcier vont tenter de percer à jour les défenses de Voldemort. Pour les aider dans cette délicate entreprise, Dumbledore va relancer et manipuler son ancien collègue, le Professeur Horace Slughorn, qu'il croit en possession d'informations vitales sur le jeune Voldemort. Mais un autre \"mal\" hante cette année les étudiants :le démon de l'adolescence ! Harry est de plus en plus attiré par Ginny, qui ne laisse pas indifférent son rival, Dean Thomas ; Lavande Brown a jeté son dévolu sur Ron, mais oublié le pouvoir \"magique\" des chocolats de Romilda Vane ; Hermione, rongée par la jalousie, a décidé de cacher ses sentiments, vaille que vaille. L'amour est dans tous les coeurs - sauf un. Car un étudiant reste étrangement sourd à son appel. Dans l'ombre, il poursuit avec acharnement un but aussi mystérieux qu'inquiétant... jusqu'à l'inévitable tragédie qui bouleversera à jamais Poudlard.", 
        date:"15 juillet 2009",
    },{
        name:"Harry Poter 7 Partie 1",
        pp:"https://fr.web.img3.acsta.net/c_310_420/medias/nmedia/18/69/69/81/19590744.jpg",
        url:"https://uqload.com/embed-dks9d8ewb0lc.html",
        des:"Le pouvoir de Voldemort s'étend. Celui-ci contrôle maintenant le Ministère de la Magie et Poudlard. Harry, Ron et Hermione décident de terminer le travail commencé par Dumbledore, et de retrouver les derniers Horcruxes pour vaincre le Seigneur des Ténèbres. Mais il reste bien peu d'espoir aux trois sorciers, qui doivent réussir à tout prix.", 
        date:"24 novembre 2010",
    },{
        name:"Harry Poter 7 Partie 2",
        pp:"https://fr.web.img6.acsta.net/c_310_420/medias/nmedia/18/78/64/49/19762436.jpg",
        url:"https://uqload.com/embed-ppl0xfl0yrf6.html",
        des:"Dans la 2e Partie de cet épisode final, le combat entre les puissances du bien et du mal de l’univers des sorciers se transforme en guerre sans merci. Les enjeux n’ont jamais été si considérables et personne n’est en sécurité. Mais c’est Harry Potter qui peut être appelé pour l’ultime sacrifice alors que se rapproche l’ultime épreuve de force avec Voldemort.", 
        date:"13 juillet 2011",
    },{
        name:"Titanic",
        pp:"https://fr.web.img6.acsta.net/c_310_420/pictures/19/10/25/11/18/5224976.jpg",
        url:"https://uqload.com/embed-spb368w2j7nm.html",
        des:"Southampton, 10 avril 1912. Le paquebot le plus grand et le plus moderne du monde, réputé pour son insubmersibilité, le \"Titanic\", appareille pour son premier voyage. Quatre jours plus tard, il heurte un iceberg. A son bord, un artiste pauvre et une grande bourgeoise tombent amoureux.", 
        date:"7 janvier 1998",
    },{
        name:"Matrix 1",
        pp:"https://fr.web.img4.acsta.net/c_310_420/medias/04/34/49/043449_af.jpg",
        url:"https://uqload.com/embed-sojn5nrnfqkc.html",
        des:"Programmeur anonyme dans un service administratif le jour, Thomas Anderson devient Neo la nuit venue. Sous ce pseudonyme, il est l'un des pirates les plus recherchés du cyber-espace. A cheval entre deux mondes, Neo est assailli par d'étranges songes et des messages cryptés provenant d'un certain Morpheus. Celui-ci l'exhorte à aller au-delà des apparences et à trouver la réponse à la question qui hante constamment ses pensées : qu'est-ce que la Matrice ? Nul ne le sait, et aucun homme n'est encore parvenu à en percer les defenses. Mais Morpheus est persuadé que Neo est l'Elu, le libérateur mythique de l'humanité annoncé selon la prophétie. Ensemble, ils se lancent dans une lutte sans retour contre la Matrice et ses terribles agents...", 
        date:"24 mai 1999",
    },{
        name:"Matrix 2",
        pp:"https://fr.web.img6.acsta.net/c_310_420/medias/nmedia/00/02/53/34/affiche.jpg",
        url:"https://uqload.com/embed-0ub36kjcm73j.html",
        des:"Neo apprend à mieux contrôler ses dons naturels, alors même que Sion s'apprête à tomber sous l'assaut de l'Armée des Machines. D'ici quelques heures, 250 000 Sentinelles programmées pour anéantir notre espèce envahiront la dernière enclave humaine de la Terre.Mais Morpheus galvanise les citoyens de Sion en leur rappelant la Parole de l'Oracle : il est encore temps pour l'Elu d'arrêter la guerre contre les Machines. Tous les espoirs se reportent dès lors sur Neo. Au long de sa périlleuse plongée au sein de la Matrix et de sa propre destinée, ce dernier sera confronté à une résistance croissante, une vérité encore plus aveuglante, un choix encore plus douloureux que tout ce qu'il avait jamais imaginé.", 
        date:"16 mai 2003",
    },{
        name:"Matrix 3",
        pp:"https://fr.web.img5.acsta.net/c_310_420/medias/nmedia/18/35/14/64/18364977.jpg",
        url:"https://uqload.com/embed-rwfz76t9pbg5.html",
        des:"La longue quête de liberté des rebelles culmine en une bataille finale explosive. Tandis que l'armée des Machines sème la désolation sur Zion, ses citoyens organisent une défense acharnée. Mais pourront-ils retenir les nuées implacables des Sentinelles en attendant que Neo s'approprie l'ensemble de ses pouvoirs et mette fin à la guerre ?L'agent Smith est quant à lui parvenu à prendre possession de l'esprit de Bane, l'un des membres de l'équipage de l'aéroglisseur. De plus en plus puissant, il est désormais incontrôlable et n'obéit plus aux Machines : il menace de détruire leur empire ainsi que le monde réel et la Matrice...", 
        date:"5 novembre 2003",
    },{
        name:"Matrix 4",
        pp:"https://fr.web.img2.acsta.net/c_310_420/pictures/21/11/17/17/24/3336846.jpg",
        url:"https://uqload.com/embed-jlh4cwu4zany.html",
        des:"MATRIX RESURRECTIONS nous replonge dans deux réalités parallèles – celle de notre quotidien et celle du monde qui s’y dissimule. Pour savoir avec certitude si sa réalité propre est une construction physique ou mentale, et pour véritablement se connaître lui-même, M. Anderson devra de nouveau suivre le lapin blanc. Et si Thomas... Neo... a bien appris quelque chose, c’est qu’une telle décision, quoique illusoire, est la seule manière de s’extraire de la Matrice – ou d’y entrer... Bien entendu, Neo sait déjà ce qui lui reste à faire. Ce qu’il ignore en revanche, c’est que la Matrice est plus puissante, plus sécurisée et plus redoutable que jamais. Comme un air de déjà vu...", 
        date:"22 décembre 2021",
    },{
        name:"Shazam",
        pp:"https://fr.web.img2.acsta.net/c_310_420/pictures/19/03/11/16/43/1722757.jpg",
        url:"https://uqload.com/embed-flg7dztlqm9y.html",
        des:"On a tous un super-héros qui sommeille au fond de soi… il faut juste un peu de magie pour le réveiller. Pour Billy Batson, gamin débrouillard de 14 ans placé dans une famille d'accueil, il suffit de crier \"Shazam !\" pour se transformer en super-héros.Ado dans un corps d'adulte sculpté à la perfection, Shazam s'éclate avec ses tout nouveaux superpouvoirs. Est-il capable de voler ? De voir à travers n'importe quel type de matière ? De faire jaillir la foudre de ses mains ? Et de sauter son examen de sciences sociales ? Shazam repousse les limites de ses facultés avec l'insouciance d'un enfant. Mais il lui faudra maîtriser rapidement ses pouvoirs pour combattre les forces des ténèbres du Dr Thaddeus Sivana…", 
        date:"3 avril 2019",
    },{
        name:"Pirate des Caraibes",
        pp:"https://fr.web.img2.acsta.net/c_310_420/medias/nmedia/18/35/07/46/affiche2.jpg",
        url:"https://uqload.com/embed-snc0x67d192l.html",
        des:"Dans la mer des Caraïbes, au XVIIe siècle, Jack Sparrow, flibustier gentleman, voit sa vie idyllique basculer le jour où son ennemi, le perfide capitaine Barbossa, lui vole son bateau, le Black Pearl, puis attaque la ville de Port Royal, enlevant au passage la très belle fille du gouverneur, Elizabeth Swann. L'ami d'enfance de celle-ci, Will Turner, se joint à Jack pour se lancer aux trousses du capitaine.Mais Will ignore qu'une malédiction frappe Barbossa et ses pirates. Lorsque la lune brille, ils se transforment en morts-vivants. Leur terrible sort ne prendra fin que le jour où le fabuleux trésor qu'ils ont amassé sera restitué...", 
        date:"13 août 2003",
    },{
        name:"Pirate des Caraibes 2",
        pp:"https://fr.web.img4.acsta.net/c_310_420/medias/nmedia/18/36/00/56/18604499.jpg",
        url:"https://uqload.com/embed-0cbxk4pkt39x.html",
        des:"Dans ce nouvel opus de l'aventure Pirates des Caraïbes, le toujours aussi excentrique pirate Jack Sparrow est confronté subitement à son passé. Treize ans auparavant, Jack signait un pacte avec Davey Jones, le maître des sept mers, dont l'esprit maléfique n'a d'égal que son apparence tentaculaire. En échange de son âme, ce dernier lui promettait le commandement du mythique Black Pearl...Aujourd'hui, Jones vient donc récupérer sa dette. Mais donner son âme à Jones est sans issue, il n'y a pas de rédemption possible, c'est devenir comme tous les membres de son équipage maudit, un fantôme au physique aussi repoussant que terrifiant. Pour éviter ce sort funeste auquel Jack ne tient pas vraiment, il n'a qu'une solution : retrouver le coffre maudit de Jones où sont cachés les âmes emprisonnées...", 
        date:"2 août 2006",
    },{
        name:"Pirate des Caraibes 3",
        pp:"https://fr.web.img6.acsta.net/c_310_420/medias/nmedia/18/62/88/97/18754731.jpg",
        url:"https://uqload.com/embed-fh1cbnhczkjg.html",
        des:"L'âge d'or de la piraterie touche à sa fin. Même le terrifiant Vaisseau Fantôme et son capitaine maudit Davy Jones servent à présent Lord Cutler Beckett et la Compagnie anglaise des Indes Orientales. L'invincible Hollandais Volant écume désormais les sept mers, massacrant sans pitié pirates de tous bords et sabordant leurs navires.Will Turner, Elizabeth Swann et le capitaine Barbossa n'ont qu'une seule chance de résister à Beckett et à son armada destructrice : ils doivent rassembler les Neuf Seigneurs de la Cour des Frères, mais l'un des membres les plus éminents, le capitaine Jack Sparrow, manque à l'appel.Will, Elizabeth et Barbossa, secondés par Tia Dalma, Pintel et Ragetti, doivent faire voile vers des mers orientales inconnues, pour affronter un pirate chinois, le capitaine Sao Feng, et s'emparer des cartes qui les conduiront au-delà des limites du monde connu, là où Jack est retenu...", 
        date:"23 mai 2007",
    },{
        name:"Pirate des Caraibes 4",
        pp:"https://fr.web.img6.acsta.net/c_310_420/medias/nmedia/18/79/98/60/19713505.jpg",
        url:"https://uqload.com/embed-ak42i1zmdw03.html",
        des:"Dans cette histoire pleine d’action, où vérité, trahison, jeunesse éternelle et mort forment un cocktail explosif, le capitaine Jack Sparrow retrouve une femme qu’il a connue autrefois. Leurs liens sont-ils faits d’amour ou cette femme n’est-elle qu’une aventurière sans scrupules qui cherche à l’utiliser pour découvrir la légendaire Fontaine de Jouvence ? Lorsqu’elle l’oblige à embarquer à bord du Queen Anne’s Revenge, le bateau du terrible pirate Barbe-Noire, Jack ne sait plus ce qu’il doit craindre le plus : le redoutable maître du bateau ou cette femme surgie de son passé...", 
        date:"18 mai 2011",
    },{
        name:"Pirate des Caraibes 5",
        pp:"https://fr.web.img6.acsta.net/c_310_420/pictures/17/03/02/10/13/106609.jpg",
        url:"https://uqload.com/embed-6sdah3jyqhgu.html",
        des:"Les temps sont durs pour le Capitaine Jack, et le destin semble même vouloir s’acharner lorsqu’un redoutable équipage fantôme mené par son vieil ennemi, le terrifiant Capitaine Salazar, s’échappe du Triangle du Diable pour anéantir tous les flibustiers écumant les flots… Sparrow compris ! Le seul espoir de survie du Capitaine Jack est de retrouver le légendaire Trident de Poséidon, qui donne à celui qui le détient tout pouvoir sur les mers et les océans. Mais pour cela, il doit forger une alliance précaire avec Carina Smyth, une astronome aussi belle que brillante, et Henry, un jeune marin de la Royal Navy au caractère bien trempé. À la barre du Dying Gull, un minable petit rafiot, Sparrow va tout entreprendre pour contrer ses revers de fortune, mais aussi sauver sa vie face au plus implacable ennemi qu’il ait jamais eu à affronter…", 
        date:"24 mai 2017",
    },{
        name:"Taxi",
        pp:"https://fr.web.img3.acsta.net/c_310_420/medias/nmedia/00/02/49/22/affiche.jpg",
        url:"https://uqload.com/embed-jzn0jnxrtq01.html",
        des:"Daniel est un fou du volant. Cet ex-livreur de pizzas est aujourd'hui chauffeur de taxi et sait échapper aux radars les plus perfectionnés. Pourtant, un jour, il croise la route d'Emilien, policier recalé pour la huitième fois à son permis de conduire. Pour conserver son taxi, il accepte le marché que lui propose Emilien : l'aider à démanteler un gang de braqueurs de banques qui écume les succursales de la ville à bord de puissants véhicules. Road-movie urbain sur un scénario de Luc Besson, également producteur.", 
        date:"8 avril 1998",
    },{
        name:"Taxi 2",
        pp:"https://fr.web.img6.acsta.net/c_310_420/medias/nmedia/18/63/24/72/18962752.jpg",
        url:"https://uqload.com/embed-83iqt19l8cuh.html",
        des:"La ravissante Lily va enfin présenter Daniel à son père, un important général de l'armée française. Or, Daniel est retardé par une femme enceinte qui accouche dans son taxi. Malgré tout, le jeune homme réussit à séduire son simili-beau-père, mais le repas est brusquement interrompu car le général doit accueillir le Ministre japonais de la défense. Daniel le conduit à l'aéroport à une vitesse record. Il y retrouve son copain Emilien, policier toujours aussi dévoué, mais guère efficace.", 
        date:"29 mars 2000",
    },{
        name:"Taxi 3",
        pp:"https://fr.web.img4.acsta.net/c_310_420/medias/nmedia/00/02/57/84/affiche.jpg",
        url:"https://uqload.com/embed-6tylmceed246.html",
        des:"Marseille, à l'approche de Noël. Daniel ne cesse de rajouter des gadgets à son taxi. Au point de faire passer son bolide avant sa compagne, Lilly, qui décide de retourner vivre chez ses parents. Petra, elle, reproche à Emilien d'avoir la tête ailleurs. Celui-ci enrage en effet de ne pas avoir encore arrêté le gang des pères Noël, qui multiplie les braquages depuis huit mois.", 
        date:"29 janvier 2003",
    },{
        name:"Taxi 4",
        pp:"https://fr.web.img6.acsta.net/c_310_420/medias/nmedia/18/63/73/33/18723066.jpg",
        url:"https://uqload.com/embed-p5izpz1fvqyl.html",
        des:"De l'eau a coulé sous les ponts depuis la dernière aventure de Daniel et Emilien : les deux hommes sont désormais pères de famille et ont du mal à s'occuper de leurs fils, deux sacrés canailles. Une chose n'a pas changé cependant : Emilien est toujours le policier le plus maladroit et malchanceux de Marseille et Daniel le conducteur de taxi le plus rapide. Les deux hommes vont devoir faire équipe afin d'arrêter un terrifiant braqueur de banque surnommé \"Le Belge\"...", 
        date:"14 février 2007",
    },{
        name:"Taxi 5",
        pp:"https://fr.web.img6.acsta.net/c_310_420/pictures/18/03/09/12/16/2548759.jpg",
        url:"https://uqload.com/embed-5mmnqd3xzar8.html",
        des:"Sylvain Marot, super flic parisien et pilote d’exception, est muté contre son gré à la Police Municipale de Marseille. L’ex-commissaire Gibert, devenu Maire de la ville et au plus bas dans les sondages, va alors lui confier la mission de stopper le redoutable « Gang des Italiens », qui écume des bijouteries à l’aide de puissantes Ferrari.", 
        date:"7 avril 2018",
    },{
        name:"Paddington",
        pp:"https://fr.web.img3.acsta.net/c_310_420/pictures/14/12/05/10/53/508053.jpg",
        url:"https://uqload.com/embed-8v82s1ju3429.html",
        des:"Paddington raconte l'histoire d'un jeune ours péruvien fraîchement débarqué à Londres, à la recherche d'un foyer et d'une vie meilleure. Il réalise vite que la ville de ses rêves n'est pas aussi accueillante qu'il croyait. Par chance, il rencontre la famille Brown et en devient peu à peu un membre à part entière.      ", 
        date:"3 décembre 2014",
    },{
        name:"Paddington 2",
        pp:"https://fr.web.img6.acsta.net/c_310_420/pictures/17/11/14/10/08/1496521.jpg",
        url:"https://uqload.com/embed-8v3s6vwjyqfw.html",
        des:"Paddington coule des jours heureux chez les Brown, sa famille d’adoption, dans un quartier paisible de Londres, où il est apprécié de tous. Alors qu’il recherche un cadeau exceptionnel pour les cent ans de sa tante adorée, il repère un magnifique livre animé, très ancien, chez un antiquaire. Pas de temps à perdre : il enchaîne les petits boulots pour pouvoir l’acheter ! Mais lorsque le précieux ouvrage est volé, Paddington est accusé à tort et incarcéré. Convaincus de son innocence, les Brown se lancent dans une enquête pour retrouver le coupable…", 
        date:"6 décembre 2017",
    },{
        name:"Men in Black",
        pp:"https://fr.web.img3.acsta.net/c_310_420/pictures/14/05/26/16/57/120603.jpg",
        url:"https://uqload.com/embed-u8mmjeevpga2.html",
        des:"Chargés de protéger la Terre de toute infraction extraterrestre et de réguler l'immigration intergalactique sur notre planète, les Men in black ou MIB opèrent dans le plus grand secret. Vêtus de costumes sombres et équipés des toutes dernières technologies, ils passent inaperçus aux yeux des humains dont ils effacent régulièrement la mémoire récente : la présence d'aliens sur notre sol doit rester secrète.Récemment séparé de son vieux partenaire, retourné à la vie civile sans aucun souvenir de sa vie d'homme en noir, K, le plus expérimenté des agents du MIB décide de former J, un jeune policier. Ensemble, ils vont affronter une nouvelle menace : Edgar le cafard...", 
        date:"6 août 1997",
    },{
        name:"Men in Black 2",
        pp:"https://fr.web.img6.acsta.net/c_310_420/medias/nmedia/00/02/33/46/af.jpg",
        url:"https://uqload.com/embed-9vmpe57eapm2.html",
        des:".En quatre années passées à protéger la Terre de toutes sortes d'invasion extraterrestre, l'agent J, qui travaille secrètement au quartier général des Men in black, n'a toujours pas trouvé de partenaire avec qui faire équipe. A la suite d'un crime étrange impliquant des extraterrestres, l'agence découvre l'existence d'un redoutable complot menaçant notre planète. Serleena, une maléfique séductrice qui a pris l'apparence d'un top-model en lingerie fine, est prête à tout pour accomplir son sinistre dessein. J a absolument besoin des services de K, son ancien partenaire qui n'a plus aucun souvenir des MIB et travaille dorénavant à la Poste. J va devoir par tous les moyens le faire sortir de sa retraite.", 
        date:"7 août 2002",
    },{
        name:"Men in Black 3",
        pp:"https://fr.web.img6.acsta.net/c_310_420/medias/nmedia/18/89/36/03/20072335.jpg",
        url:"https://uqload.com/embed-nj6stjfcwo3w.html",
        des:"En quinze ans de carrière chez les Men in Black, l’agent J a vu beaucoup de phénomènes inexplicables… Mais rien, pas même le plus étrange des aliens, ne le laisse aussi perplexe que son partenaire, le sarcastique K.Lorsque la vie de K et le destin de la Terre sont menacés, l’agent J décide de remonter le temps pour remettre les choses en ordre. Il va alors découvrir qu’il existe certains secrets de l’univers que K ne lui a jamais révélés. Il est cette fois obligé de faire équipe avec l’agent K, plus jeune, pour sauver la vie de son partenaire, l’agence, et l’avenir même de l’humanité…", 
        date:"12 mai 2012",
    },{
        name:"Men in Black 4",
        pp:"https://fr.web.img6.acsta.net/c_310_420/pictures/19/04/25/11/42/1533005.jpg",
        url:"https://uqload.com/embed-8fdzgptf0i8z.html",
        des:"Chargés de protéger la Terre de toute infraction extraterrestre et de réguler l'immigration intergalactique sur notre planète, les Men in black ou MIB opèrent dans le plus grand secret. Vêtus de costumes sombres et équipés des toutes dernières technologies, ils passent inaperçus aux yeux des humains dont ils effacent régulièrement la mémoire récente : la présence d'aliens sur notre sol doit rester secrète.Récemment séparé de son vieux partenaire, retourné à la vie civile sans aucun souvenir de sa vie d'homme en noir, K, le plus expérimenté des agents du MIB décide de former J, un jeune policier. Ensemble, ils vont affronter une nouvelle menace : Edgar le cafard...", 
        date:": 12 juin 2019",
    },{
        name:"Les Animaux Fantastiques",
        pp:"https://fr.web.img6.acsta.net/c_310_420/pictures/16/10/11/09/32/205295.jpg",
        url:"https://uqload.com/embed-a2qpbjno0wjb.html",
        des:"LNew York, 1926. Le monde des sorciers est en grand danger. Une force mystérieuse sème le chaos dans les rues de la ville : la communauté des sorciers risque désormais d'être à la merci des Fidèles de Salem, groupuscule fanatique des Non-Maj’ (version américaine du \"Moldu\") déterminé à les anéantir. Quant au redoutable sorcier Gellert Grindelwald, après avoir fait des ravages en Europe, il a disparu… et demeure introuvable.Ignorant tout de ce conflit qui couve, Norbert Dragonneau débarque à New York au terme d'un périple à travers le monde : il a répertorié un bestiaire extraordinaire de créatures fantastiques dont certaines sont dissimulées dans les recoins magiques de sa sacoche en cuir – en apparence – banale. Mais quand Jacob Kowalski, Non-Maj’ qui ne se doute de rien, libère accidentellement quelques créatures dans les rues de la ville, la catastrophe est imminente. Il s'agit d'une violation manifeste du Code International du Secret Magique dont se saisit l'ancienne Auror Tina Goldstein pour récupérer son poste d'enquêtrice. Et la situation s'aggrave encore lorsque Percival Graves, énigmatique directeur de la Sécurité du MACUSA (Congrès Magique des États-Unis d'Amérique), se met à soupçonner Norbert… et Tina.Norbert, Tina et sa sœur Queenie, accompagnés de leur nouvel ami Non-Maj’ Jacob, unissent leurs forces pour retrouver les créatures disséminées dans la nature avant qu'il ne leur arrive malheur. Mais nos quatre héros involontaires, dorénavant considérés comme fugitifs, doivent surmonter des obstacles bien plus importants qu’ils n’ont jamais imaginé. Car ils s'apprêtent à affronter des forces des ténèbres qui risquent bien de déclencher une guerre entre les Non-Maj’ et le monde des sorciers.", 
        date:"16 novembre 2016",
    },{
        name:"Les Animaux Fantastiques 2",
        pp:"https://fr.web.img4.acsta.net/c_310_420/pictures/18/10/10/11/16/4794693.jpg",
        url:"https://uqload.com/embed-88zgyiv5lmco.html",
        des:"1927. Quelques mois après sa capture, le célèbre sorcier Gellert Grindelwald s'évade comme il l'avait promis et de façon spectaculaire. Réunissant de plus en plus de partisans, il est à l'origine d'attaque d'humains normaux par des sorciers et seul celui qu'il considérait autrefois comme un ami, Albus Dumbledore, semble capable de l'arrêter. Mais Dumbledore va devoir faire appel au seul sorcier ayant déjoué les plans de Grindelwald auparavant : son ancien élève Norbert Dragonneau. L'aventure qui les attend réunit Norbert avec Tina, Queenie et Jacob, mais cette mission va également tester la loyauté de chacun face aux nouveaux dangers qui se dressent sur leur chemin, dans un monde magique plus dangereux et divisé que jamais.", 
        date:"14 novembre 2018",
    },{
        name:"Black Panther",
        pp:"https://fr.web.img6.acsta.net/c_310_420/pictures/17/10/16/15/40/0883250.jpg",
        url:"https://uqload.com/embed-ttsqb2t53oya.html",
        des:"Après les événements qui se sont déroulés dans Captain America : Civil War, T’Challa revient chez lui prendre sa place sur le trône du Wakanda, une nation africaine technologiquement très avancée. Mais lorsqu’un vieil ennemi resurgit, le courage de T’Challa est mis à rude épreuve, aussi bien en tant que souverain qu’en tant que Black Panther. Il se retrouve entraîné dans un conflit qui menace non seulement le destin du Wakanda, mais celui du monde entier…", 
        date:"14 février 2018",
    },{
        name:"Valérian et la Cité des Mille Planètes",
        pp:"https://fr.web.img6.acsta.net/c_310_420/pictures/17/05/24/09/19/550722.jpg",
        url:"https://uqload.com/embed-mi81oi8cl35q.html",
        des:"Au 28ème siècle, Valérian et Laureline forment une équipe d'agents spatio-temporels chargés de maintenir l'ordre dans les territoires humains. Mandaté par le Ministre de la Défense, le duo part en mission sur l’extraordinaire cité intergalactique Alpha...", 
        date:"26 juillet 2017",
    },{
        name:"Seul sur Mars",
        pp:"https://fr.web.img6.acsta.net/c_310_420/pictures/15/09/08/15/20/305329.jpg",
        url:"https://uqload.com/embed-f00hzywfg7ye.html",
        des:"Lors d’une expédition sur Mars, l’astronaute Mark Watney (Matt Damon) est laissé pour mort par ses coéquipiers, une tempête les ayant obligés à décoller en urgence. Mais Mark a survécu et il est désormais seul, sans moyen de repartir, sur une planète hostile. Il va devoir faire appel à son intelligence et son ingéniosité pour tenter de survivre et trouver un moyen de contacter la Terre. A 225 millions de kilomètres, la NASA et des scientifiques du monde entier travaillent sans relâche pour le sauver, pendant que ses coéquipiers tentent d’organiser une mission pour le récupérer au péril de leurs vies.", 
        date:"21 octobre 2015",
    },{
        name:"Intouchable",
        pp:"https://fr.web.img3.acsta.net/c_310_420/o_club300-310x420.png_0_se/medias/nmedia/18/82/69/17/19806656.jpg",
        url:"https://uqload.com/embed-imtk5prxs7ke.html",
        des:"A la suite d’un accident de parapente, Philippe, riche aristocrate, engage comme aide à domicile Driss, un jeune de banlieue tout juste sorti de prison. Bref la personne la moins adaptée pour le job. Ensemble ils vont faire cohabiter Vivaldi et Earth Wind and Fire, le verbe et la vanne, les costumes et les bas de survêtement... Deux univers vont se télescoper, s’apprivoiser, pour donner naissance à une amitié aussi dingue, drôle et forte qu’inattendue, une relation unique qui fera des étincelles et qui les rendra... Intouchables.", 
        date:" 2 novembre 2011",
    },{
        name:"Jumanji 1996",
        pp:"https://fr.web.img6.acsta.net/c_310_420/pictures/14/08/14/12/20/198981.jpg",
        url:"https://uqload.com/embed-ou4xibav2qig.html",
        des:"Lors d'une partie de Jumanji, un jeu très ancien, le jeune Alan est propulsé sous les yeux de son amie d'enfance, Sarah, dans un étrange pays. Il ne pourra s'en échapper que lorsqu'un autre joueur reprendra la partie et le libèrera sur un coup de dés. Vingt-six ans plus tard, il retrouve le monde réel par le coup de dés de deux autres jeunes joueurs.", 
        date:"14 février 1996",
    },{
        name:"Jumanji 2017",
        pp:"https://fr.web.img4.acsta.net/c_310_420/pictures/17/11/07/13/40/0517792.jpg",
        url:"https://uqload.com/embed-rrwzksmocf1p.html",
        des:"Le destin de quatre lycéens en retenue bascule lorsqu’ils sont aspirés dans le monde de Jumanji. Après avoir découvert une vieille console contenant un jeu vidéo dont ils n’avaient jamais entendu parler, les quatre jeunes se retrouvent mystérieusement propulsés au cœur de la jungle de Jumanji, dans le corps de leurs avatars. Ils vont rapidement découvrir que l’on ne joue pas à Jumanji, c’est le jeu qui joue avec vous… Pour revenir dans le monde réel, il va leur falloir affronter les pires dangers et triompher de l’ultime aventure. Sinon, ils resteront à jamais prisonniers de Jumanji…", 
        date:"20 décembre 2017",
    },{
        name:"Jumanji 2019",
        pp:"https://fr.web.img2.acsta.net/c_310_420/pictures/19/11/07/12/52/2054035.jpg",
        url:"https://uqload.com/embed-oiopiqbsu2oa.html",
        des:"L'équipe est de retour mais le jeu a changé. Alors qu'ils retournent dans Jumanji pour secourir l'un des leurs, ils découvrent un monde totalement inattendu. Des déserts arides aux montagnes enneigées, les joueurs vont devoir braver des espaces inconnus et inexplorés, afin de sortir du jeu le plus dangereux du monde.", 
        date:"4 décembre 2019",
    },{
        name:"Top Gun",
        pp:"https://fr.web.img4.acsta.net/c_310_420/pictures/15/06/12/12/58/422779.jpg",
        url:"https://uqload.com/embed-x1rannm1fumb.html",
        des:"Jeune as du pilotage et tête brûlée d'une école réservée à l'élite de l'aéronavale US (\"Top Gun\"), Pete Mitchell, dit \"Maverick\", tombe sous le charme d'une instructrice alors qu'il est en compétition pour le titre du meilleur pilote...", 
        date:"17 septembre 1986",
    },{
        name:"Le Cinquieme Element",
        pp:"https://fr.web.img4.acsta.net/c_310_420/pictures/14/08/21/14/17/385506.jpg",
        url:"https://uqload.com/embed-x1rannm1fumb.html",
        des:"Au XXIII siècle, dans un univers étrange et coloré, où tout espoir de survie est impossible sans la découverte du cinquième élément, un héros affronte le mal pour sauver l'humanité.      ", 
        date:"7 mai 1997",
    },{
        name:"Le Diner des Cons",
        pp:"https://fr.web.img5.acsta.net/c_310_420/medias/nmedia/18/36/10/96/19649758.jpg",
        url:"https://uqload.com/embed-zgdxky2i2lji.html",
        des:"Tous les mercredis, Pierre Brochant et ses amis organisent un dîner où chacun doit amener un con. Celui qui a trouvé le plus spectaculaire est declaré vainqueur. Ce soir, Brochant exulte, il est sur d'avoir trouvé la perle rare, un con de classe mondiale: Francois Pignon, comptable au ministère des Finances et passionné de modèles réduits en allumettes. Ce qu'il ignore c'est que Pignon est passe maître dans l'art de déclencher des catastrophes.", 
        date:"15 avril 1998",
    },{
        name:"Aladin",
        pp:"https://fr.web.img6.acsta.net/c_310_420/pictures/19/04/19/09/29/4029006.jpg",
        url:"https://uqload.com/embed-3oc2z8ev764x.html",
        des:"Quand un charmant garçon des rues du nom d’Aladdin cherche à conquérir le cœur de la belle, énigmatique et fougueuse princesse Jasmine, il fait appel au tout puissant Génie, le seul qui puisse lui permettre de réaliser trois vœux, dont celui de devenir le prince Ali pour mieux accéder au palais…", 
        date:"22 mai 2019",
    },{
        name:"RAID Dingue",
        pp:"https://fr.web.img5.acsta.net/c_310_420/pictures/17/01/06/12/46/346064.jpg",
        url:"https://uqload.com/embed-g3mgf47fkcag.html",
        des:"Johanna Pasquali est une fliquette pas comme les autres. Distraite, rêveuse et maladroite, elle est d'un point de vue purement policier sympathique mais totalement nulle. Dotée pourtant de réelles compétences, sa maladresse fait d'elle une menace pour les criminels, le grand public et ses collègues.Assignée à des missions aussi dangereuses que des voitures mal garées ou des vols à l'étalage, elle s'entraîne sans relâche pendant son temps libre pour réaliser son rêve : être la première femme à intégrer le groupe d'élite du RAID.Acceptée au centre de formation du RAID pour des raisons obscures et politiques, elle se retrouve alors dans les pattes de l'agent Eugène Froissard (dit Poissard), le plus misogyne des agents du RAID. Ce duo improbable se voit chargé d'arrêter le redoutable Gang des Léopards, responsable de gros braquages dans les rues de la capitale.Mais avant de pouvoir les arrêter, il faudrait déjà qu'ils parviennent à travailler en binôme sans s'entretuer au cours des entraînements ou des missions de terrain plus rocambolesques les unes que les autres.", 
        date:"1 janvier 2016",
    },{
        name:"Qu'est-ce qu'on a ENCORE fait au bon dieu",
        pp:"https://fr.web.img6.acsta.net/c_310_420/pictures/18/10/30/09/17/3442022.jpg",
        url:"https://uqload.com/embed-smeq58romhs3.html",
        des:"Le retour des familles Verneuil et Koffi au grand complet !Claude et Marie Verneuil font face à une nouvelle crise.Leurs quatre gendres, Rachid, David, Chao et Charles sont décidés à quitter la France avec femmes et enfants pour tenter leur chance à l’étranger.Incapables d’imaginer leur famille loin d’eux, Claude et Marie sont prêts à tout pour les retenir.De leur côté, les Koffi débarquent en France pour le mariage de leur fille. Eux non plus ne sont pas au bout de leurs surprises…", 
        date:"30 janvier 2019",
    },{
        name:"Passengers",
        pp:"https://fr.web.img6.acsta.net/c_310_420/pictures/16/12/14/16/45/405336.jpg",
        url:"https://uqload.com/embed-45z3p3fw1xt6.html",
        des:"lors que 5000 passagers endormis pour longtemps voyagent dans l’espace vers une nouvelle planète, deux d’entre eux sont accidentellement tirés de leur sommeil artificiel 90 ans trop tôt. Jim et Aurora doivent désormais accepter l’idée de passer le reste de leur existence à bord du vaisseau spatial. Alors qu’ils éprouvent peu à peu une indéniable attirance, ils découvrent que le vaisseau court un grave danger. La vie des milliers de passagers endormis est entre leurs mains…", 
        date:"28 décembre 2016",
    },{
        name:"Pixels",
        pp:"https://fr.web.img3.acsta.net/c_310_420/pictures/15/06/19/11/04/234477.jpg",
        url:"https://uqload.com/embed-v202wze7j729.html",
        des:"À l’époque de leur jeunesse, dans les années 80, Sam Brenner, Will Cooper, Ludlow Lamonsoff et Eddie « Fire Blaster » Plant ont sauvé le monde des milliers de fois… en jouant à des jeux d’arcade à 25 cents la partie. Mais aujourd’hui, ils vont devoir le faire pour de vrai… Lorsque des aliens découvrent des vidéos d’anciens jeux et les prennent pour une déclaration de guerre, ils lancent l’assaut contre la Terre. Ces mêmes jeux d’arcade leur servent de modèles pour leurs attaques. Cooper, qui est désormais Président des États-Unis, fait alors appel à ses vieux potes pour empêcher la destruction de la planète par PAC-MAN, Donkey Kong, Galaga, Centipede et les Space Invaders… Les gamers pourront compter sur l’aide du lieutenant-colonel Violet Van Patten, une spécialiste qui va leur fournir des armes uniques...", 
        date:"22 juillet 2015",
    },{
        name:"Mulan 2020",
        pp:"https://fr.web.img6.acsta.net/c_310_420/pictures/19/12/05/17/24/2034927.jpg",
        url:"https://uqload.com/embed-naiyy0vryxu4.html",
        des:"Lorsque l’Empereur de Chine publie un décret stipulant qu’un homme de chaque famille du pays doit intégrer l’armée impériale pour combattre des envahisseurs venus du nord, Hua Mulan, fille ainée d’un vénérable guerrier désormais atteint par la maladie, décide de prendre sa place au combat. Se faisant passer pour un soldat du nom de Hua Jun, elle se voit mise à l’épreuve à chaque étape du processus d’apprentissage, mobilisant chaque jour un peu plus sa force intérieure pour explorer son véritable potentiel…Commence alors pour Mulan un voyage épique qui transformera la jeune fille en une guerrière aux faits d’armes héroïques, honorée par tout un peuple reconnaissant et faisant la fierté de son père.", 
        date:"30 novembre 2020",
    },{
        name:"Maman j'ai rater l'avion",
        pp:"https://fr.web.img3.acsta.net/c_310_420/pictures/17/11/15/15/14/4627669.jpg",
        url:"https://uqload.com/embed-cvykbqtr8se6.html",
        des:"La famille McCallister a decidé de passer les fêtes de Noel à Paris. Seulement Kate et Peter McCallister s'aperçoivent dans l'avion qu'il leur manque le plus jeune de leurs enfants, Kevin, âgé de 9 ans. D'abord désespéré, Kevin reprend vite les choses en main et s'organise pour vivre le mieux possible. Quand deux cambrioleurs choisissent sa maison pour commettre leurs méfaits.", 
        date:"19 décembre 1990",
    },{
        name:"Maman j'ai rater l'avion 2",
        pp:"https://fr.web.img2.acsta.net/c_310_420/pictures/19/01/16/13/47/0129993.jpg",
        url:"https://uqload.com/embed-42skexoy598c.html",
        des:"Après Paris, c'est à Miami que la tribu McCallister décide de passer les fêtes de Noël. A l'aube du jour J, toute la famille est sur le pied de guerre et file a l'aéroport en prenant bien garde de ne pas oublier Kevin. Mais celui-ci s'éclipse pour acheter des piles pour son walkman, il ne retrouve plus les siens et s'embarque par mégarde pour New York...", 
        date:"16 décembre 1992",
    },{
        name:"Kick Ass",
        pp:"https://fr.web.img5.acsta.net/c_310_420/o_club300-310x420.png_0_se/medias/nmedia/18/68/16/06/19397107.jpg",
        url:"https://uqload.com/embed-vdxskgvciocs.html",
        des:"Dave Lizewski est un adolescent gavé de comics qui ne vit que pour ce monde de super-héros et d'incroyables aventures. Décidé à vivre son obsession jusque dans la réalité, il se choisit un nom – Kick-Ass – se fabrique lui-même un costume, et se lance dans une bataille effrénée contre le crime. Dans son délire, il n'a qu'un seul problème : Kick-Ass n'a pas le moindre superpouvoir... Le voilà pourchassé par toutes les brutes de la ville. Mais Kick-Ass s'associe bientôt à d'autres délirants copycats décidés eux aussi à faire régner la justice. Parmi eux, une enfant de 11 ans, Hit Girl et son père Big Daddy, mais aussi Red Mist. Le parrain de la mafia locale, Frank D'Amico, va leur donner l'occasion de montrer ce dont ils sont capables...", 
        date:"21 avril 2010",
    }
]
module.exports = film

// , {
//     name:"",
//     pp:"",
//     url:"",
//     des:"",
//     date:"",
//      }
//https://fr.web.img6.acsta.net/c_310_420/commons/v9/common/empty/empty_portrait.png